# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AllClinicalEntity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """AllClinicalEntity - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AllClinicalEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllClinicalEntity of this AllClinicalEntity.  # noqa: E501
        :rtype: AllClinicalEntity
        """
        return util.deserialize_model(dikt, cls)
