# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Diff(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orph_acode: int=None):  # noqa: E501
        """Diff - a model defined in Swagger

        :param orph_acode: The orph_acode of this Diff.  # noqa: E501
        :type orph_acode: int
        """
        self.swagger_types = {
            'orph_acode': int
        }

        self.attribute_map = {
            'orph_acode': 'ORPHAcode'
        }
        self._orph_acode = orph_acode

    @classmethod
    def from_dict(cls, dikt) -> 'Diff':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Diff of this Diff.  # noqa: E501
        :rtype: Diff
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this Diff.


        :return: The orph_acode of this Diff.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this Diff.


        :param orph_acode: The orph_acode of this Diff.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode
