# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityByIcd11(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, code_icd11: str=None, references: List=None):  # noqa: E501
        """EntityByIcd11 - a model defined in Swagger

        :param _date: The _date of this EntityByIcd11.  # noqa: E501
        :type _date: datetime
        :param code_icd11: The code_icd11 of this EntityByIcd11.  # noqa: E501
        :type code_icd11: str
        :param references: The references of this EntityByIcd11.  # noqa: E501
        :type references: List
        """
        self.swagger_types = {
            '_date': datetime,
            'code_icd11': str,
            'references': List
        }

        self.attribute_map = {
            '_date': 'Date',
            'code_icd11': 'Code ICD11',
            'references': 'References'
        }
        self.__date = _date
        self._code_icd11 = code_icd11
        self._references = references

    @classmethod
    def from_dict(cls, dikt) -> 'EntityByIcd11':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity_by_icd11 of this EntityByIcd11.  # noqa: E501
        :rtype: EntityByIcd11
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this EntityByIcd11.


        :return: The _date of this EntityByIcd11.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this EntityByIcd11.


        :param _date: The _date of this EntityByIcd11.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def code_icd11(self) -> str:
        """Gets the code_icd11 of this EntityByIcd11.


        :return: The code_icd11 of this EntityByIcd11.
        :rtype: str
        """
        return self._code_icd11

    @code_icd11.setter
    def code_icd11(self, code_icd11: str):
        """Sets the code_icd11 of this EntityByIcd11.


        :param code_icd11: The code_icd11 of this EntityByIcd11.
        :type code_icd11: str
        """

        self._code_icd11 = code_icd11

    @property
    def references(self) -> List:
        """Gets the references of this EntityByIcd11.


        :return: The references of this EntityByIcd11.
        :rtype: List
        """
        return self._references

    @references.setter
    def references(self, references: List):
        """Sets the references of this EntityByIcd11.


        :param references: The references of this EntityByIcd11.
        :type references: List
        """

        self._references = references
