# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityBySnomed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, code_omim: int=None):  # noqa: E501
        """EntityBySnomed - a model defined in Swagger

        :param _date: The _date of this EntityBySnomed.  # noqa: E501
        :type _date: datetime
        :param code_omim: The code_omim of this EntityBySnomed.  # noqa: E501
        :type code_omim: int
        """
        self.swagger_types = {
            '_date': datetime,
            'code_omim': int
        }

        self.attribute_map = {
            '_date': 'Date',
            'code_omim': 'Code OMIM'
        }
        self.__date = _date
        self._code_omim = code_omim

    @classmethod
    def from_dict(cls, dikt) -> 'EntityBySnomed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity_by_snomed of this EntityBySnomed.  # noqa: E501
        :rtype: EntityBySnomed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this EntityBySnomed.


        :return: The _date of this EntityBySnomed.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this EntityBySnomed.


        :param _date: The _date of this EntityBySnomed.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def code_omim(self) -> int:
        """Gets the code_omim of this EntityBySnomed.


        :return: The code_omim of this EntityBySnomed.
        :rtype: int
        """
        return self._code_omim

    @code_omim.setter
    def code_omim(self, code_omim: int):
        """Sets the code_omim of this EntityBySnomed.


        :param code_omim: The code_omim of this EntityBySnomed.
        :type code_omim: int
        """

        self._code_omim = code_omim
