# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityByIcd10(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, code_icd10: str=None):  # noqa: E501
        """EntityByIcd10 - a model defined in Swagger

        :param _date: The _date of this EntityByIcd10.  # noqa: E501
        :type _date: datetime
        :param code_icd10: The code_icd10 of this EntityByIcd10.  # noqa: E501
        :type code_icd10: str
        """
        self.swagger_types = {
            '_date': datetime,
            'code_icd10': str
        }

        self.attribute_map = {
            '_date': 'Date',
            'code_icd10': 'Code ICD10'
        }
        self.__date = _date
        self._code_icd10 = code_icd10

    @classmethod
    def from_dict(cls, dikt) -> 'EntityByIcd10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity_by_icd10 of this EntityByIcd10.  # noqa: E501
        :rtype: EntityByIcd10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this EntityByIcd10.


        :return: The _date of this EntityByIcd10.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this EntityByIcd10.


        :param _date: The _date of this EntityByIcd10.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def code_icd10(self) -> str:
        """Gets the code_icd10 of this EntityByIcd10.


        :return: The code_icd10 of this EntityByIcd10.
        :rtype: str
        """
        return self._code_icd10

    @code_icd10.setter
    def code_icd10(self, code_icd10: str):
        """Sets the code_icd10 of this EntityByIcd10.


        :param code_icd10: The code_icd10 of this EntityByIcd10.
        :type code_icd10: str
        """

        self._code_icd10 = code_icd10
