# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Icd10References(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code_icd10: str=None, disorder_mapping_relation: str=None, disorder_mapping_icd_relation: str=None, disorder_mapping_validation_status: str=None):  # noqa: E501
        """Icd10References - a model defined in Swagger

        :param code_icd10: The code_icd10 of this Icd10References.  # noqa: E501
        :type code_icd10: str
        :param disorder_mapping_relation: The disorder_mapping_relation of this Icd10References.  # noqa: E501
        :type disorder_mapping_relation: str
        :param disorder_mapping_icd_relation: The disorder_mapping_icd_relation of this Icd10References.  # noqa: E501
        :type disorder_mapping_icd_relation: str
        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this Icd10References.  # noqa: E501
        :type disorder_mapping_validation_status: str
        """
        self.swagger_types = {
            'code_icd10': str,
            'disorder_mapping_relation': str,
            'disorder_mapping_icd_relation': str,
            'disorder_mapping_validation_status': str
        }

        self.attribute_map = {
            'code_icd10': 'Code ICD10',
            'disorder_mapping_relation': 'DisorderMappingRelation',
            'disorder_mapping_icd_relation': 'DisorderMappingICDRelation',
            'disorder_mapping_validation_status': 'DisorderMappingValidationStatus'
        }
        self._code_icd10 = code_icd10
        self._disorder_mapping_relation = disorder_mapping_relation
        self._disorder_mapping_icd_relation = disorder_mapping_icd_relation
        self._disorder_mapping_validation_status = disorder_mapping_validation_status

    @classmethod
    def from_dict(cls, dikt) -> 'Icd10References':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The icd10_References of this Icd10References.  # noqa: E501
        :rtype: Icd10References
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_icd10(self) -> str:
        """Gets the code_icd10 of this Icd10References.


        :return: The code_icd10 of this Icd10References.
        :rtype: str
        """
        return self._code_icd10

    @code_icd10.setter
    def code_icd10(self, code_icd10: str):
        """Sets the code_icd10 of this Icd10References.


        :param code_icd10: The code_icd10 of this Icd10References.
        :type code_icd10: str
        """

        self._code_icd10 = code_icd10

    @property
    def disorder_mapping_relation(self) -> str:
        """Gets the disorder_mapping_relation of this Icd10References.


        :return: The disorder_mapping_relation of this Icd10References.
        :rtype: str
        """
        return self._disorder_mapping_relation

    @disorder_mapping_relation.setter
    def disorder_mapping_relation(self, disorder_mapping_relation: str):
        """Sets the disorder_mapping_relation of this Icd10References.


        :param disorder_mapping_relation: The disorder_mapping_relation of this Icd10References.
        :type disorder_mapping_relation: str
        """
        allowed_values = ["E", "NTBT", "BTNT", "NTBT/E", "BTNT/E", "ND"]  # noqa: E501
        if disorder_mapping_relation not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_relation` ({0}), must be one of {1}"
                .format(disorder_mapping_relation, allowed_values)
            )

        self._disorder_mapping_relation = disorder_mapping_relation

    @property
    def disorder_mapping_icd_relation(self) -> str:
        """Gets the disorder_mapping_icd_relation of this Icd10References.


        :return: The disorder_mapping_icd_relation of this Icd10References.
        :rtype: str
        """
        return self._disorder_mapping_icd_relation

    @disorder_mapping_icd_relation.setter
    def disorder_mapping_icd_relation(self, disorder_mapping_icd_relation: str):
        """Sets the disorder_mapping_icd_relation of this Icd10References.


        :param disorder_mapping_icd_relation: The disorder_mapping_icd_relation of this Icd10References.
        :type disorder_mapping_icd_relation: str
        """
        allowed_values = ["Specific code", "Inclusion term", "Index term", "Attributed"]  # noqa: E501
        if disorder_mapping_icd_relation not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_icd_relation` ({0}), must be one of {1}"
                .format(disorder_mapping_icd_relation, allowed_values)
            )

        self._disorder_mapping_icd_relation = disorder_mapping_icd_relation

    @property
    def disorder_mapping_validation_status(self) -> str:
        """Gets the disorder_mapping_validation_status of this Icd10References.


        :return: The disorder_mapping_validation_status of this Icd10References.
        :rtype: str
        """
        return self._disorder_mapping_validation_status

    @disorder_mapping_validation_status.setter
    def disorder_mapping_validation_status(self, disorder_mapping_validation_status: str):
        """Sets the disorder_mapping_validation_status of this Icd10References.


        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this Icd10References.
        :type disorder_mapping_validation_status: str
        """
        allowed_values = ["Validated", "Not yet validated"]  # noqa: E501
        if disorder_mapping_validation_status not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_validation_status` ({0}), must be one of {1}"
                .format(disorder_mapping_validation_status, allowed_values)
            )

        self._disorder_mapping_validation_status = disorder_mapping_validation_status
