# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityByIcd(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """EntityByIcd - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EntityByIcd':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity_by_icd of this EntityByIcd.  # noqa: E501
        :rtype: EntityByIcd
        """
        return util.deserialize_model(dikt, cls)
