# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityByIcdReferencesOrpha(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orph_acode: int=None, preferred_term: str=None, disorder_mapping_relation: str=None, disorder_mapping_icd_relation: str=None, disorder_mapping_validation_status: str=None):  # noqa: E501
        """EntityByIcdReferencesOrpha - a model defined in Swagger

        :param orph_acode: The orph_acode of this EntityByIcdReferencesOrpha.  # noqa: E501
        :type orph_acode: int
        :param preferred_term: The preferred_term of this EntityByIcdReferencesOrpha.  # noqa: E501
        :type preferred_term: str
        :param disorder_mapping_relation: The disorder_mapping_relation of this EntityByIcdReferencesOrpha.  # noqa: E501
        :type disorder_mapping_relation: str
        :param disorder_mapping_icd_relation: The disorder_mapping_icd_relation of this EntityByIcdReferencesOrpha.  # noqa: E501
        :type disorder_mapping_icd_relation: str
        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this EntityByIcdReferencesOrpha.  # noqa: E501
        :type disorder_mapping_validation_status: str
        """
        self.swagger_types = {
            'orph_acode': int,
            'preferred_term': str,
            'disorder_mapping_relation': str,
            'disorder_mapping_icd_relation': str,
            'disorder_mapping_validation_status': str
        }

        self.attribute_map = {
            'orph_acode': 'ORPHAcode',
            'preferred_term': 'Preferred term',
            'disorder_mapping_relation': 'DisorderMappingRelation',
            'disorder_mapping_icd_relation': 'DisorderMappingICDRelation',
            'disorder_mapping_validation_status': 'DisorderMappingValidationStatus'
        }
        self._orph_acode = orph_acode
        self._preferred_term = preferred_term
        self._disorder_mapping_relation = disorder_mapping_relation
        self._disorder_mapping_icd_relation = disorder_mapping_icd_relation
        self._disorder_mapping_validation_status = disorder_mapping_validation_status

    @classmethod
    def from_dict(cls, dikt) -> 'EntityByIcdReferencesOrpha':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity_by_icd_References Orpha of this EntityByIcdReferencesOrpha.  # noqa: E501
        :rtype: EntityByIcdReferencesOrpha
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this EntityByIcdReferencesOrpha.


        :return: The orph_acode of this EntityByIcdReferencesOrpha.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this EntityByIcdReferencesOrpha.


        :param orph_acode: The orph_acode of this EntityByIcdReferencesOrpha.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this EntityByIcdReferencesOrpha.


        :return: The preferred_term of this EntityByIcdReferencesOrpha.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this EntityByIcdReferencesOrpha.


        :param preferred_term: The preferred_term of this EntityByIcdReferencesOrpha.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term

    @property
    def disorder_mapping_relation(self) -> str:
        """Gets the disorder_mapping_relation of this EntityByIcdReferencesOrpha.


        :return: The disorder_mapping_relation of this EntityByIcdReferencesOrpha.
        :rtype: str
        """
        return self._disorder_mapping_relation

    @disorder_mapping_relation.setter
    def disorder_mapping_relation(self, disorder_mapping_relation: str):
        """Sets the disorder_mapping_relation of this EntityByIcdReferencesOrpha.


        :param disorder_mapping_relation: The disorder_mapping_relation of this EntityByIcdReferencesOrpha.
        :type disorder_mapping_relation: str
        """
        allowed_values = ["E", "NTBT", "BTNT", "NTBT/E", "BTNT/E", "ND"]  # noqa: E501
        if disorder_mapping_relation not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_relation` ({0}), must be one of {1}"
                .format(disorder_mapping_relation, allowed_values)
            )

        self._disorder_mapping_relation = disorder_mapping_relation

    @property
    def disorder_mapping_icd_relation(self) -> str:
        """Gets the disorder_mapping_icd_relation of this EntityByIcdReferencesOrpha.


        :return: The disorder_mapping_icd_relation of this EntityByIcdReferencesOrpha.
        :rtype: str
        """
        return self._disorder_mapping_icd_relation

    @disorder_mapping_icd_relation.setter
    def disorder_mapping_icd_relation(self, disorder_mapping_icd_relation: str):
        """Sets the disorder_mapping_icd_relation of this EntityByIcdReferencesOrpha.


        :param disorder_mapping_icd_relation: The disorder_mapping_icd_relation of this EntityByIcdReferencesOrpha.
        :type disorder_mapping_icd_relation: str
        """
        allowed_values = ["Specific code", "Inclusion term", "Index term", "Attributed"]  # noqa: E501
        if disorder_mapping_icd_relation not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_icd_relation` ({0}), must be one of {1}"
                .format(disorder_mapping_icd_relation, allowed_values)
            )

        self._disorder_mapping_icd_relation = disorder_mapping_icd_relation

    @property
    def disorder_mapping_validation_status(self) -> str:
        """Gets the disorder_mapping_validation_status of this EntityByIcdReferencesOrpha.


        :return: The disorder_mapping_validation_status of this EntityByIcdReferencesOrpha.
        :rtype: str
        """
        return self._disorder_mapping_validation_status

    @disorder_mapping_validation_status.setter
    def disorder_mapping_validation_status(self, disorder_mapping_validation_status: str):
        """Sets the disorder_mapping_validation_status of this EntityByIcdReferencesOrpha.


        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this EntityByIcdReferencesOrpha.
        :type disorder_mapping_validation_status: str
        """
        allowed_values = ["Validated", "Not yet validated"]  # noqa: E501
        if disorder_mapping_validation_status not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_validation_status` ({0}), must be one of {1}"
                .format(disorder_mapping_validation_status, allowed_values)
            )

        self._disorder_mapping_validation_status = disorder_mapping_validation_status
