# coding: utf-8

from __future__ import absolute_import
from datetime import datetime  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FindbyOMIMInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, status: str=None, preferred_term: str=None, definition: str=None, disorder_mapping_relation: str=None, disorder_mapping_validation_status: str=None):  # noqa: E501
        """FindbyOMIMInner - a model defined in Swagger

        :param _date: The _date of this FindbyOMIMInner.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this FindbyOMIMInner.  # noqa: E501
        :type orph_acode: int
        :param status: The status of this FindbyOMIMInner.  # noqa: E501
        :type status: str
        :param preferred_term: The preferred_term of this FindbyOMIMInner.  # noqa: E501
        :type preferred_term: str
        :param definition: The definition of this FindbyOMIMInner.  # noqa: E501
        :type definition: str
        :param disorder_mapping_relation: The disorder_mapping_relation of this FindbyOMIMInner.  # noqa: E501
        :type disorder_mapping_relation: str
        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this FindbyOMIMInner.  # noqa: E501
        :type disorder_mapping_validation_status: str
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'status': str,
            'preferred_term': str,
            'definition': str,
            'disorder_mapping_relation': str,
            'disorder_mapping_validation_status': str
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'status': 'Status',
            'preferred_term': 'Preferred term',
            'definition': 'Definition',
            'disorder_mapping_relation': 'DisorderMappingRelation',
            'disorder_mapping_validation_status': 'DisorderMappingValidationStatus'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._status = status
        self._preferred_term = preferred_term
        self._definition = definition
        self._disorder_mapping_relation = disorder_mapping_relation
        self._disorder_mapping_validation_status = disorder_mapping_validation_status

    @classmethod
    def from_dict(cls, dikt) -> 'FindbyOMIMInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindbyOMIM_inner of this FindbyOMIMInner.  # noqa: E501
        :rtype: FindbyOMIMInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this FindbyOMIMInner.


        :return: The _date of this FindbyOMIMInner.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this FindbyOMIMInner.


        :param _date: The _date of this FindbyOMIMInner.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this FindbyOMIMInner.


        :return: The orph_acode of this FindbyOMIMInner.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this FindbyOMIMInner.


        :param orph_acode: The orph_acode of this FindbyOMIMInner.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def status(self) -> str:
        """Gets the status of this FindbyOMIMInner.


        :return: The status of this FindbyOMIMInner.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this FindbyOMIMInner.


        :param status: The status of this FindbyOMIMInner.
        :type status: str
        """
        allowed_values = ["Active", "Active_Historical entity", "Inactive_Deprecated entity", "Inactive_Obsolete entity", "Inactive_Non Rare disease in Europe"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this FindbyOMIMInner.


        :return: The preferred_term of this FindbyOMIMInner.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this FindbyOMIMInner.


        :param preferred_term: The preferred_term of this FindbyOMIMInner.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term

    @property
    def definition(self) -> str:
        """Gets the definition of this FindbyOMIMInner.


        :return: The definition of this FindbyOMIMInner.
        :rtype: str
        """
        return self._definition

    @definition.setter
    def definition(self, definition: str):
        """Sets the definition of this FindbyOMIMInner.


        :param definition: The definition of this FindbyOMIMInner.
        :type definition: str
        """

        self._definition = definition

    @property
    def disorder_mapping_relation(self) -> str:
        """Gets the disorder_mapping_relation of this FindbyOMIMInner.


        :return: The disorder_mapping_relation of this FindbyOMIMInner.
        :rtype: str
        """
        return self._disorder_mapping_relation

    @disorder_mapping_relation.setter
    def disorder_mapping_relation(self, disorder_mapping_relation: str):
        """Sets the disorder_mapping_relation of this FindbyOMIMInner.


        :param disorder_mapping_relation: The disorder_mapping_relation of this FindbyOMIMInner.
        :type disorder_mapping_relation: str
        """
        allowed_values = ["E", "NTBT", "BTNT", "NTBT/E", "BTNT/E", "ND"]  # noqa: E501
        if disorder_mapping_relation not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_relation` ({0}), must be one of {1}"
                .format(disorder_mapping_relation, allowed_values)
            )

        self._disorder_mapping_relation = disorder_mapping_relation

    @property
    def disorder_mapping_validation_status(self) -> str:
        """Gets the disorder_mapping_validation_status of this FindbyOMIMInner.


        :return: The disorder_mapping_validation_status of this FindbyOMIMInner.
        :rtype: str
        """
        return self._disorder_mapping_validation_status

    @disorder_mapping_validation_status.setter
    def disorder_mapping_validation_status(self, disorder_mapping_validation_status: str):
        """Sets the disorder_mapping_validation_status of this FindbyOMIMInner.


        :param disorder_mapping_validation_status: The disorder_mapping_validation_status of this FindbyOMIMInner.
        :type disorder_mapping_validation_status: str
        """
        allowed_values = ["Validated", "Not yet validated"]  # noqa: E501
        if disorder_mapping_validation_status not in allowed_values:
            raise ValueError(
                "Invalid value for `disorder_mapping_validation_status` ({0}), must be one of {1}"
                .format(disorder_mapping_validation_status, allowed_values)
            )

        self._disorder_mapping_validation_status = disorder_mapping_validation_status
