# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.icd10_code_icd import ICD10CodeICD  # noqa: F401,E501
from swagger_server import util


class ICD10(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: datetime=None, orph_acode: int=None, orphanet_url: str=None, code_icd: List[ICD10CodeICD]=None):  # noqa: E501
        """ICD10 - a model defined in Swagger

        :param _date: The _date of this ICD10.  # noqa: E501
        :type _date: datetime
        :param orph_acode: The orph_acode of this ICD10.  # noqa: E501
        :type orph_acode: int
        :param orphanet_url: The orphanet_url of this ICD10.  # noqa: E501
        :type orphanet_url: str
        :param code_icd: The code_icd of this ICD10.  # noqa: E501
        :type code_icd: List[ICD10CodeICD]
        """
        self.swagger_types = {
            '_date': datetime,
            'orph_acode': int,
            'orphanet_url': str,
            'code_icd': List[ICD10CodeICD]
        }

        self.attribute_map = {
            '_date': 'Date',
            'orph_acode': 'ORPHAcode',
            'orphanet_url': 'OrphanetURL',
            'code_icd': 'Code ICD'
        }
        self.__date = _date
        self._orph_acode = orph_acode
        self._orphanet_url = orphanet_url
        self._code_icd = code_icd

    @classmethod
    def from_dict(cls, dikt) -> 'ICD10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ICD10 of this ICD10.  # noqa: E501
        :rtype: ICD10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this ICD10.


        :return: The _date of this ICD10.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this ICD10.


        :param _date: The _date of this ICD10.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this ICD10.


        :return: The orph_acode of this ICD10.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this ICD10.


        :param orph_acode: The orph_acode of this ICD10.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def orphanet_url(self) -> str:
        """Gets the orphanet_url of this ICD10.


        :return: The orphanet_url of this ICD10.
        :rtype: str
        """
        return self._orphanet_url

    @orphanet_url.setter
    def orphanet_url(self, orphanet_url: str):
        """Sets the orphanet_url of this ICD10.


        :param orphanet_url: The orphanet_url of this ICD10.
        :type orphanet_url: str
        """

        self._orphanet_url = orphanet_url

    @property
    def code_icd(self) -> List[ICD10CodeICD]:
        """Gets the code_icd of this ICD10.


        :return: The code_icd of this ICD10.
        :rtype: List[ICD10CodeICD]
        """
        return self._code_icd

    @code_icd.setter
    def code_icd(self, code_icd: List[ICD10CodeICD]):
        """Sets the code_icd of this ICD10.


        :param code_icd: The code_icd of this ICD10.
        :type code_icd: List[ICD10CodeICD]
        """

        self._code_icd = code_icd
