# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Parent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orph_acode: int=None, preferred_term: str=None, id_of_the_classification: int=None, name_of_the_classification: str=None, parent_orph_acode: int=None, parent_preferred_term: str=None):  # noqa: E501
        """Parent - a model defined in Swagger

        :param orph_acode: The orph_acode of this Parent.  # noqa: E501
        :type orph_acode: int
        :param preferred_term: The preferred_term of this Parent.  # noqa: E501
        :type preferred_term: str
        :param id_of_the_classification: The id_of_the_classification of this Parent.  # noqa: E501
        :type id_of_the_classification: int
        :param name_of_the_classification: The name_of_the_classification of this Parent.  # noqa: E501
        :type name_of_the_classification: str
        :param parent_orph_acode: The parent_orph_acode of this Parent.  # noqa: E501
        :type parent_orph_acode: int
        :param parent_preferred_term: The parent_preferred_term of this Parent.  # noqa: E501
        :type parent_preferred_term: str
        """
        self.swagger_types = {
            'orph_acode': int,
            'preferred_term': str,
            'id_of_the_classification': int,
            'name_of_the_classification': str,
            'parent_orph_acode': int,
            'parent_preferred_term': str
        }

        self.attribute_map = {
            'orph_acode': 'ORPHAcode',
            'preferred_term': 'Preferred term',
            'id_of_the_classification': 'ID of the classification',
            'name_of_the_classification': 'Name of the classification',
            'parent_orph_acode': 'Parent ORPHAcode',
            'parent_preferred_term': 'Parent preferred term'
        }
        self._orph_acode = orph_acode
        self._preferred_term = preferred_term
        self._id_of_the_classification = id_of_the_classification
        self._name_of_the_classification = name_of_the_classification
        self._parent_orph_acode = parent_orph_acode
        self._parent_preferred_term = parent_preferred_term

    @classmethod
    def from_dict(cls, dikt) -> 'Parent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parent of this Parent.  # noqa: E501
        :rtype: Parent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orph_acode(self) -> int:
        """Gets the orph_acode of this Parent.


        :return: The orph_acode of this Parent.
        :rtype: int
        """
        return self._orph_acode

    @orph_acode.setter
    def orph_acode(self, orph_acode: int):
        """Sets the orph_acode of this Parent.


        :param orph_acode: The orph_acode of this Parent.
        :type orph_acode: int
        """

        self._orph_acode = orph_acode

    @property
    def preferred_term(self) -> str:
        """Gets the preferred_term of this Parent.


        :return: The preferred_term of this Parent.
        :rtype: str
        """
        return self._preferred_term

    @preferred_term.setter
    def preferred_term(self, preferred_term: str):
        """Sets the preferred_term of this Parent.


        :param preferred_term: The preferred_term of this Parent.
        :type preferred_term: str
        """

        self._preferred_term = preferred_term

    @property
    def id_of_the_classification(self) -> int:
        """Gets the id_of_the_classification of this Parent.


        :return: The id_of_the_classification of this Parent.
        :rtype: int
        """
        return self._id_of_the_classification

    @id_of_the_classification.setter
    def id_of_the_classification(self, id_of_the_classification: int):
        """Sets the id_of_the_classification of this Parent.


        :param id_of_the_classification: The id_of_the_classification of this Parent.
        :type id_of_the_classification: int
        """

        self._id_of_the_classification = id_of_the_classification

    @property
    def name_of_the_classification(self) -> str:
        """Gets the name_of_the_classification of this Parent.


        :return: The name_of_the_classification of this Parent.
        :rtype: str
        """
        return self._name_of_the_classification

    @name_of_the_classification.setter
    def name_of_the_classification(self, name_of_the_classification: str):
        """Sets the name_of_the_classification of this Parent.


        :param name_of_the_classification: The name_of_the_classification of this Parent.
        :type name_of_the_classification: str
        """

        self._name_of_the_classification = name_of_the_classification

    @property
    def parent_orph_acode(self) -> int:
        """Gets the parent_orph_acode of this Parent.


        :return: The parent_orph_acode of this Parent.
        :rtype: int
        """
        return self._parent_orph_acode

    @parent_orph_acode.setter
    def parent_orph_acode(self, parent_orph_acode: int):
        """Sets the parent_orph_acode of this Parent.


        :param parent_orph_acode: The parent_orph_acode of this Parent.
        :type parent_orph_acode: int
        """

        self._parent_orph_acode = parent_orph_acode

    @property
    def parent_preferred_term(self) -> str:
        """Gets the parent_preferred_term of this Parent.


        :return: The parent_preferred_term of this Parent.
        :rtype: str
        """
        return self._parent_preferred_term

    @parent_preferred_term.setter
    def parent_preferred_term(self, parent_preferred_term: str):
        """Sets the parent_preferred_term of this Parent.


        :param parent_preferred_term: The parent_preferred_term of this Parent.
        :type parent_preferred_term: str
        """

        self._parent_preferred_term = parent_preferred_term
