# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FindbyOMIM(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """FindbyOMIM - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'FindbyOMIM':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindbyOMIM of this FindbyOMIM.  # noqa: E501
        :rtype: FindbyOMIM
        """
        return util.deserialize_model(dikt, cls)
